spring:
  cloud:
    stream:
      bindings:
        input:
          destination: users
        output:
          destination: users

    gcp:
      pubsub:
        credentials:
          location: gcp-pubsub-cred.json

